// examples/react/src/App.tsx
import { useState } from 'react';
import './App.css';
import PaginationTest from '@saurssaurav/pagination-js-react';
import '@saurssaurav/pagination-js-core/style.css';

function App() {
  const [currentPage, setCurrentPage] = useState(1);

const onChange = (page:number) => {
  setCurrentPage(page);
};
  return (
    <>
 <PaginationTest
    totalPage={10}
    pageSidesToCurrentPage={1}
    currentPage={currentPage}
    onChangeCurrentPage={onChange}
  ></PaginationTest>
    </>
  );
}

export default App;

// packages/vue-example/src/App.vue
<script setup lang="ts">
import { ref } from 'vue';
import PaginationTest from '@saurssaurav/pagination-js-vue';
import '@saurssaurav/pagination-js-core/style.css';
const currentPage = ref(1);

const onChange = (page) => {
  currentPage.value = page;
};
</script>

<template>
  <div> Test </div>
  <pagination-test
    :totalPage="10"
    :pageSidesToCurrentPage="2"
    :currentPage="currentPage"
    @onChangeCurrentPage="onChange"
  ></pagination-test>
</template>

<style scoped></style>
