// examples/vue/src/App.vue
<script setup lang="ts">
import { ref } from 'vue';
import PaginationTest from '@saurssaurav/pagination-js-vue';
import '@saurssaurav/pagination-js-core/style.css'; // import default pagination css

const currentPage = ref(1);

const onChange = (page) => {
  currentPage.value = page;
};
</script>

<template>
  <pagination-test
    :totalPage="10"
    :pageSidesToCurrentPage="1"
    :currentPage="currentPage"
    @onChangeCurrentPage="onChange"
  ></pagination-test>
</template>

// packages/react/src/App.tsx
import { getPaginationWithEllipsisArray } from '@saurssaurav/pagination-js-core';
import { EmitProps, Props } from './types';

function App(props: Props & EmitProps) {
  const paginationWithEllipsisArray = getPaginationWithEllipsisArray({
    currentPage: props.currentPage,
    pageSidesToCurrentPage: props.pageSidesToCurrentPage,
    totalPage: props.totalPage
  })

  const onCurrentPageChange = (page: number | string) => {
    if (typeof page === 'string') {
      return;
    }
    if (page > props.totalPage || page < 1) {
      return;
    }

    props.onChangeCurrentPage(page)

  };

  const isActive = (page: number | string) => {
    if (typeof page === 'string') {
      return;
    }
    if (page === props.currentPage) {
      return true;
    }
  };
  

  return (
    <>
     <div className="pagination">
    <div className="pagination__page pagination__page--first" onClick={() => {onCurrentPageChange(props.currentPage - 1)}}>&lt;</div>
    {paginationWithEllipsisArray.map(pagination =>{
      return (
        <div
  
      className={`pagination__page ${isActive(pagination)? 'pagination__page--active':''}`}
      onClick={() =>{onCurrentPageChange(pagination)}}
    >
      { pagination }
    </div>
      )
    })}
    <div className="pagination__page" onClick={() =>{onCurrentPageChange(props.currentPage + 1)}}> &gt; </div>
     </div>
    </>
  );
}

export default App;
